# Generated by Django 5.1.15 on 2026-09-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150, verbose_name='用户名')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='IP 地址')),
                ('success', models.BooleanField(default=False, verbose_name='是否成功')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '登录尝试',
                'verbose_name_plural': '登录尝试',
                'ordering': ['-created_at'],
            },
        ),
    ]
